In [1]:
from comp7405.basic import *
from comp7405.asian import *

np.random.seed(7405)

# Test Cases

In [2]:
S0 = 100
K = 100
T = 3
sigma = np.array([0.3, 0.3, 0.3, 0.4])
r = 0.05
n = np.array([1, 50, 100, 50])

# Test Closed Form Geometic Asian Option Formula


In [3]:
print(black_scholes(S0, K, T, sigma, r, q=0.0, option_type='C'))
print(black_scholes(S0, K, T, sigma, r, q=0.0, option_type='P'))
print(geom_asian_exact(S0, K, T, sigma, r, n, option_type='C'))
print(geom_asian_exact(S0, K, T, sigma, r, n, option_type='P'))

[ 26.8054836   26.8054836   26.8054836   32.73804437]
[ 12.87628124  12.87628124  12.87628124  18.80884201]
[ 26.8054836   13.25912613  13.13877911  15.75981978]
[ 12.87628124   8.48270454   8.43108016  12.55876944]


1. For `n` = 1, Geometric Asian option price should be the same as European.
2. The larger the `n`, the lsser the effective time to maturity, so the option prices should be smaller.
3. For a higher `sigma`, the price should be higher.

# Test Monte Carlo Simulation (Geometric Asian)

First, see if we can achieve the closed form geometric asian option formula result.

In [4]:
for i in range(4):
    print(geom_asian_exact(S0, K, T, sigma[i], r, n[i], option_type='C'))
    print(monte_carlo_asian(S0, K, T, sigma[i], r, n[i], option_type='C', sim_type='G'))
    print(geom_asian_exact(S0, K, T, sigma[i], r, n[i], option_type='P'))
    print(monte_carlo_asian(S0, K, T, sigma[i], r, n[i], option_type='P', sim_type='G'))


26.8054835966
(26.487580517221865, 26.204238512949207, 26.770922521494523)
12.8762812391
(12.904372027301477, 12.796802382205973, 13.011941672396981)
13.2591261305
(13.27925150978839, 13.1495997117577, 13.408903307819079)
8.48270454488
(8.4665366142023029, 8.3932197626002232, 8.5398534658043825)
13.1387791144
(13.138100502012703, 13.010010646311979, 13.266190357713427)
8.43108015568
(8.4241066124805499, 8.3512424026715486, 8.4969708222895513)
15.7598197764
(15.650745117142787, 15.477674448799355, 15.823815785486218)
12.5587694397
(12.58939761028283, 12.492886389519574, 12.685908831046087)


The more the no. of simulation, the closer to the theoratical values, and the samller the confidence interval.

In [5]:
print(geom_asian_exact(S0, K, T, sigma[0], r, n[0], option_type='C'))
V, l, u = monte_carlo_asian(S0, K, T, sigma[0], r, n[0], option_type='C', sim_type='G', m=100)
print (V, u-l)
V, l, u = monte_carlo_asian(S0, K, T, sigma[0], r, n[0], option_type='C', sim_type='G', m=1000)
print (V, u-l)
V, l, u = monte_carlo_asian(S0, K, T, sigma[0], r, n[0], option_type='C', sim_type='G', m=10000)
print (V, u-l)
V, l, u = monte_carlo_asian(S0, K, T, sigma[0], r, n[0], option_type='C', sim_type='G', m=100000)
print (V, u-l)

26.8054835966
24.5606373693 16.1953007934
27.4692582956 5.60105966554
27.1044132758 1.83322343418
26.7060467888 0.568178522199


# Test Monte Carlo Simulation (Arithmetric Asian)

For `n` = 1, Arithmetic Asian option should be simular to Black-Sholes formula result.

In [6]:
print(black_scholes(S0, K, T, sigma[0], r, q=0.0, option_type='C'))
print(black_scholes(S0, K, T, sigma[0], r, q=0.0, option_type='P'))
print(monte_carlo_asian(S0, K, T, sigma[0], r, n=1, option_type='C', sim_type='A'))
print(monte_carlo_asian(S0, K, T, sigma[0], r, n=1, option_type='P', sim_type='A'))

26.8054835966
12.8762812391
(26.572284137766491, 26.291956386506783, 26.8526118890262)
(12.819488951358512, 12.712164185190238, 12.926813717526786)


Generally, 
- Arithmetic asian call price should be higher than Geometric asian call price.
- Arithmetic asian put price should be higher than Geometric asian put price.

In [7]:
for i in range(1,4):
    print(geom_asian_exact(S0, K, T, sigma[i], r, n[i], option_type='C'))
    print(monte_carlo_asian(S0, K, T, sigma[i], r, n[i], option_type='C', sim_type='G'))
    print(monte_carlo_asian(S0, K, T, sigma[i], r, n[i], option_type='C', sim_type='A'))
    print(geom_asian_exact(S0, K, T, sigma[i], r, n[i], option_type='P'))
    print(monte_carlo_asian(S0, K, T, sigma[i], r, n[i], option_type='P', sim_type='G'))
    print(monte_carlo_asian(S0, K, T, sigma[i], r, n[i], option_type='P', sim_type='A'))
    print()


13.2591261305
(13.201846276112155, 13.072963618298729, 13.330728933925581)
(14.721755656579468, 14.578053962642217, 14.865457350516719)
8.48270454488
(8.4375780506803597, 8.364509153420121, 8.5106469479405984)
(7.7947397804814678, 7.7256705442062747, 7.8638090167566608)

13.1387791144
(13.105659137311298, 12.978388311693896, 13.232929962928699)
(14.643722160590588, 14.500493360639716, 14.786950960541461)
8.43108015568
(8.4112060444418315, 8.3383058739610885, 8.4841062149225746)
(7.7871138860059048, 7.7183894934601627, 7.855838278551647)

15.7598197764
(15.969595779733407, 15.793284721908119, 16.145906837558694)
(18.20621808659682, 18.005472323306943, 18.406963849886697)
12.5587694397
(12.527037011335358, 12.430480382525598, 12.623593640145117)
(11.292142142878966, 11.20225705017638, 11.382027235581551)



# Test Monte Carlo Simulation (Arithmetric Asian with Control Variate)

The mean should be simular to the version without control variate, but the confidence interval be much smaller

In [8]:
for i in range(4):
    mu, low, up = monte_carlo_asian(S0, K, T, sigma[i], r, n[i], option_type='C', sim_type='A')
    print(mu, up - low)
    mu, low, up = monte_carlo_asian(S0, K, T, sigma[i], r, n[i], option_type='C', sim_type='C')
    print(mu, up - low)
    mu, low, up = monte_carlo_asian(S0, K, T, sigma[i], r, n[i], option_type='P', sim_type='A')
    print(mu, up - low)
    mu, low, up = monte_carlo_asian(S0, K, T, sigma[i], r, n[i], option_type='P', sim_type='C')
    print(mu, up - low)
    print()

26.6553723747 0.566761526997
26.8054835966 0.0
12.8453875536 0.215299197453
12.8762812391 0.0

14.7404767466 0.28801234199
14.7366790366 0.0217409761883
7.76434506764 0.137858145693
7.80157383722 0.0088792510111

14.7415283113 0.286443578593
14.6119124691 0.0214225907671
7.77041711082 0.137455846281
7.74682832146 0.00884481198009

18.1118396308 0.403131177596
18.2151904296 0.0400871531328
11.3429711021 0.18001608421
11.283105215 0.0155585354059

